[book]
authors = ["Tyler Swann"]
description = "Monash DeepNeuron's High Performance Programming Curriculum"
language = "en"
multilingual = false
src = "src"
title = "High Performance Programming"
[output.html]
mathjax-support = true
